### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by Jackojc** [wotpp/wotpp#15]
We really need UTF-8 support if anyone is going to take this project seriously lol. Should be straightforward enough to implement.

**Comment by jlagarespo** [comment]
Would it be enough to replace all strings with `std::u32string` and make the lexer accept unicode characters?
I think we should introduce a compile-time flag to disable it at any rate. There should be a global `using wpp::string = <whatever>;` that can be changed with that flag.

**Comment by Jackojc** [comment]
I don't think we'd need to change all of our string types. UTF-8 is just a series of bytes after all and std::string can handle that perfectly fine. What we _would_ need to change is the lexer being able to validate and recognize UTF-8 codepoints and jump over however many bytes to the next character rather than just a simple pointer increment.

**Comment by Jackojc** [comment]
Don't think we should add a flag to disable UTF-8, it's basically the de facto encoding that everyone uses and it's backwards compatible with ASCII so I don't see the point.

**Comment by Jackojc** [comment]
Implemented in dev branch.
