### ISSUE TITLE
Variadics

### ISSUE THREAD

**Issue by Jackojc** [wotpp/wotpp#19]
Variadic functions that can accept any number of arguments:
```
let cat(single)
  single
let cat(first, ...)
  first .. cat(...)
```

**Comment by Jackojc** [comment]
Maybe use Python style notation for variadics `*`?
```
def foo(*args):
    pass
```

**Comment by Jackojc** [comment]
Maybe we should treat variadic args as a list of strings and use `car` and `cdr` like in lisp.
```
let cat(args*)
  car(args) .. cat(cdr(args)))
```

**Comment by jlagarespo** [comment]
The main problem with this is that we'd have to introduce a new list type for `car` and `cdr` to return.

**Comment by Jackojc** [comment]
Implemented in dev branch.
