### ISSUE TITLE
Issue a warning when variables are shadowing?

### ISSUE THREAD

**Issue by Jackojc** [wotpp/wotpp#50]
Would like some discussion about this.

I'm thinking of making the compiler introduce the notion of warnings which are 
non-fatal but might indicate undesired behaviour in the code.

One example of this is variable shadowing in functions. Parameters take precedence over
functions but this might not be immediately obvious to anyone so perhaps showing a
warning could be useful here. 

Probably some other cases we could issue warnings for but this is just something I 
encountered recently.

**Comment by jlagarespo** [comment]
#53
