### ISSUE TITLE
Generational functions

### ISSUE THREAD

**Issue by Jackojc** [wotpp/wotpp#54]
It might be a cool idea to have what I'm calling "generational functions" where function definitions are tracked using a stack, new functions of the same name are pushed to a stack and you can pop functions to return to a previous definition of the same name.

```
let x "foo" 
let x "bar"
x  #prints "bar"
undef x
x  #prints "foo"
```

This would let us define a function in library code for example without conflicting with other definitions a user has made.

**Comment by Jackojc** [comment]
I don't like the keyword "undef", maybe drop or discard sound a bit better?

**Comment by jlagarespo** [comment]
Perhaps `unlet` or even better, `delet`

**Comment by Jackojc** [comment]
I wonder if `previous` or `prev` could work?

**Comment by jlagarespo** [comment]
That sounds quite confusing, I personally like `drop` better.

**Comment by Jackojc** [comment]
f3263168fc98891cf66c7226f7ebc72c20a7c7d4
