### ISSUE TITLE
Unexpected behaviour with eagerly evaluated vars

### ISSUE THREAD

**Issue by jlagarespo** [wotpp/wotpp#66]
A while back a `var` keyword was introduced to replace the hacky workarounds we needed to define a function with an eagerly evaluated variable. However, (and I'm not sure if this is intended) this exhibits bizarre behaviour which I'd not normally expect.

So as I understand it, `var` is implemented the following way:
- First, the body is evaluated.
- Then, the `var` itself in the syntax tree is replaced with a function with its same name, with no arguments, and with the evaluated string as it's body.
- Then a new function is emplaced into the environment function list, with the AST node of the new pseudo-function as it's body.

If we then run something like this, we get the result I'd expect:
```wpp
var test "hi"
test # hi
var test "bye"
test # bye
drop test
test # hi
drop test
test # undefined
```

However, (and this has been throwing me off for quite a while, until I figured it out) something like this doesn't work at all:
```wpp
let def_test(x) {
    var test x
    ""
}
def_test("hi")
test # "hi", as expected
def_test("bye")
test # i'd expect "bye", but instead we get "hi" again?
drop test
test # undefined?
```

This is because after the first `def_test` is executed, this is what the code looks to the evaluator:
```wpp
let def_test(x) {
    let test "hi"
    ""
}
```

Thus, when we execute `test` the second time around, we just redefine `test` to "hi".
For now I'm gonna keep using the more traditional way:
```wpp
let def_var(name, value) eval("let " .. name .. " \"" .. escape(value) .. "\"")
```

which has the behaviour I'd expect:
```wpp
let def_test(x) {
    def_var("test", x)
    ""
}
def_test("hi")
test # hi
def_test("bye")
test # bye
drop test
test # hi
drop test
test # undefined
```

IMHO I think that this is a very hacky way of implementing var. Even more than the ~~elegant metaprogramming~~ workaround we had before. At the very least we should have a separate `Var` object (as opposed to `Fn`), which can be called from `FnInvoke`. This `Var` object wouldn't contain a `node_t` to the body, but rather the evaluated string. I also think that the AST should IN NO WAY be modified during evaluation, or else we'll always get wacky results like these.

One way or another, for now I'm gonna keep using ~~my work of art~~ the old method of defining eagerly evaluated vars.

**Comment by Jackojc** [comment]
Fixed in dev branch
